googletest: Autospec creation for update from version 1.12.1 to version 1.14.0
Aaron Jacobs (2):
      gtest.cc: add a newline after a failure when there is no OS stack trace.
      gtest.cc: run tests within a test suite in a deterministic order.

Abseil Team (87):
      Mark internal-only function as having internal linkage.
      Add support of 17-member structs to gmock UnpackStructImpl.
      Add support of 18-member structs to gmock UnpackStructImpl.
      Consider all TERM values ending in "-256color" to be color supporting. In particular this handles TERM=hterm-256color correctly.
      Fixed header guards to match style guide conventions.
      Remove obsolete MSVC warning pragmas for Invalid<T>()
      Use UnorderedElementsAre in example about using matchers with maps
      Add GoogleTest workaround for MSVC crash with Address Sanitizer (ASAN) on version 17.3.3
      Moves boilerplate disabling copy constructor/assignment from GoogleTest's TEST_P macro into a header file to avoid triggering warnings in user code.
      Uses a simpler mechanism to disable the copying of GoogleTest test suites.
      Rollback: Uses a simpler mechanism to disable the copying of GoogleTest test suites.
      Rollback: Moves boilerplate disabling copy constructor/assignment from GoogleTest's TEST_P macro into a header file to avoid triggering warnings in user code.
      Uses a simpler mechanism to disable the copying of GoogleTest test suites, to move code out of the TEST_P macro.
      Makes Clang compilations via Ninja on Windows define _DLL only for shared CRT builds, as one would already expect from MSVC builds. (Previously, static Clang/Ninja builds on Windows also implicitly defined _DLL, which was problematic.)
      [fuchsia] Use __builtin_trap to trigger gunit_break_on_failure on non-x86 arch
      Update the POSIX Extended section of the Regular Expression Wikipedia page
      Workaround for Visual C++ error C2039 with std::tuple_element_t.
      Terse printing of std::reference_wrapper hides pointer
      Adds Win32 UNC path support to FilePath::IsAbsolutePath() and FilePath::IsRootDirectory() in GoogleTest
      CMake: Add GTEST_HAS_ABSL build option for using Absl
      Clarify that parameter generator does not evaluate immediately
      Add documentation for `--gunit_recreate_environments_when_repeating`.
      Fix typo in documentation of ConvertGenerator()
      RecordProperty serializes ints and 64-bit ints, including size_ts
      Remove incorrect GTEST_ATTRIBUTE_UNUSED_ from InSequence class.
      Defined a testing::SrcDir() function that returns the name of a directory
      Remove incorrect usage of GTEST_ATTRIBUTE_UNUSED_ on classes.
      When printing floating-point numbers, print full precision by default.
      This commit fixes a minor verb conjugation error in gmock_cook_book.md.
      Disables `-Wunused-member-function` and `-Wused-but-marked-unused` that trigger via `MOCK_METHOD()` and `EXPECT_THAT()` macros.
      Make SizeIsMatcher::Impl conform to the contract of MatcherDescriberInterface.
      Introduces a new porting flag (GTEST_HAS_FILE_SYSTEM) to indicate whether a platform supports filesystem operations.
      Refactor matrix verification into VerifyMatchMatrix.
      Fix a typo in the gMock sample code for Defining a Custom Matcher Class.
      Shut up a Clang warning.
      Specify a name for a `Property` in a code example.
      Fix a typo in the documentation for "Using Predicates as Matchers".
      Use a more recent commit of googletest that uses OS constraints from
      gmock_output_test: normalize golden file output to unix line endings
      Mention using MockFunction as a way to mock free functions.
      Mention `DescribeMatcher` in matchers.md
      Make document and example code more clear in the caveat section for potential memory leak with `SetUpTestSuite`.
      Add a trailing decimal point to FormatTimeInMillisAsSeconds() output when input
      Add support for the alternative base64 encoding in RFC 4648 section 5 to `WhenBase64Unescaped`.
      Avoid reliance on <any> header without RTTI on MSVC
      Remove some filesystem APIs and tests under !GTEST_HAS_FILE_SYSTEM
      Remove strdup usage
      Fix link in ReportUninterestingCall message
      Added a missing semicolon for GTEST_FLAG_SET code snippet.
      Add `const` qualifier to `gtest_sentinel` which doesn't change.
      Reformat to current g3doc style guide. No content changes.
      Eliminate argv list action parameter.
      Rephrase the description of TEST_F() arguments for clarity.
      Internal Code Change
      Internal Code Change
      Suppress std::string DLL interface warning introduced in commit f063cd25c90cbd4089a0ff96f5991df4f2721338
      Apply clang-tidy fixes
      Add a comment to clarify Fuchsia process launcher requirement.
      Apply clang-tidy fixes
      Internal Code Change
      Fix typo in test case name.
      Remove unused using-declarations in sample unit tests
      Introduce std::make_unique and bool literals where possible
      Internal Code Change
      Fix minor bug -- if ExecDeathTestChildMain() ever returns, we should exit
      Internal Code Change
      Internal Code Change
      Replace `const char*` with `absl::string_view` as the latter is preferred.
      Update naming to "GoogleTest" in the GoogleTest Primer.
      Rolled back due to breaking existing tests.
      gtest.cc: run tests within a test suite in a deterministic order.
      Support --gtest_stream_result_to on macOS
      Fix FunctionMocker compilation slowdown in 9d21db9e0a60a1ea61ec19331c9bc0dd33e907b1
      Update gMock Cookbook to reflect deprecation of testing::ByMove
      Use Abseil Flag public API for flag parsing.
      This trips up when compiling with -Wvla otherwise.
      Give CreateArgvFromArgs internal linkage
      internal g3doc documentation change.
      Allow clients to un-suppress output from gUnit EXPECT_EXIT tests.
      Update code examples in the gMock Cookbook following C++ best practices.
      Resolve an issue where the resolution of `operator<<` overloads would attempt to instantiate the incomplete `testing::internal::Secret` type.
      Print stack traces on SEH exceptions on Windows
      Change `::testing` to `testing` in Testing Reference doc
      Make GoogleTest handle SEH exceptions before stack unwinding rather than afterward
      Update docstring of PrintWithFallback(..) to reflect the recently changed ordering.
      Make `AbslStringify` usage public in GoogleTest
      Adjust includes to use <> instead of "", consistent with quickstart pages.

Alecto Irene Perez (1):
      Fix quickstart-cmake documentation

Alexander Nikforov (2):
      cleanup from unique_ptr branch
      __cpp_char8_t does not cover std::u8string implementation, but __cpp_lib_char8_t does

Andrei Polushin (3):
      cmake: find python in order specified by PATH environment variable.
      cmake: make PDB output directory match that of a static library.
      export ThreadLocalValueHolderBase which is required by exported APIs.

Anton Sosnin (1):
      Fix typo in gmock_cook_book.md

Axel Kohlmeyer (1):
      set -utf-8 flag only for real MSVC compilers. E.g. not Intel's icx.exe

Baruch Burstein (1):
      Custom type with Combine(). Fix for #3781

Ben Yang (1):
      Update testing.md

Chris Johnson (2):
      add support for nxp qn9090 mcu
      add support for nrf52

Chris Kennelly (1):
      Enable heterogeneous lookup for RegisteredTestsMap.

Christian Clauss (2):
      Upgrade GitHub Actions Checkout
      Branding: macOS

Darryl Pogue (1):
      Set CMP0069 policy to avoid warnings

Deanna Garcia (1):
      Move transitive dependencies of googletest to googletest_deps.bzl to allow other bazel projects to depend on that rule instead of googletests' transitive dependencies directly.

Denis Hananein (7):
      Fix JSON output format #3884
      Add return for GTEST_FAIL_AT
      Allow naming expectations #3970
      Change messages
      Fix format without expectation name
      Support kitty TERM
      Change MakeUnique -> std::make_unique in docs

Derek Mauro (30):
      Update README.md for release 1.12.0
      Update version number in CMakeLists.txt
      Remove support for C++11
      Remove the Bazel provided default cxxopt -std=c++0x and replace it
      CMake: raise the default C++ standard to cxx_std_14
      Add envvar BAZEL_CXXOPTS=-std=c++14 to the GitHub Actions CI
      Add --features=external_include_paths to Bazel CI to ignore warnings
      Update README.md to point to the Foundational C++ Support Policy
      Rollback 4fa8cfe3f4dee8975ee02d98633a5245ab67c6d7
      Fix MSVC C++14 flag for GitHub workflow
      Use attribute testing to simplify portable attribute macros
      Fix detection of the no_sanitize("hwaddress") attribute
      Remove the unused class TestNameIs
      Migrate GoogleTest to a bug report template and add a link to the discussion
      Convert feature requests to a form
      Workaround for GCC12 bug illustrated by https://godbolt.org/z/Pe5aE59xG
      Update GoogleTest dependencies
      Add an explicit #error that C++ versions less than C++14 are not supported
      Bump version to 1.13.0 in preparation for release
      Update documentation for v1.13.0
      Remove FloatingPoint::Max() in favor of std::numeric_limits::max()
      Migrate CI builds to MSVC 2022
      Remove the Win64 arch from the CMake Generator since
      Fix redundant redeclaration warning
      On platforms without a file system, don't log an error when no
      Remove unused cast implementation
      Update GoogleTest dependencies
      Add googletest-message-test to the Bazel tests
      Remove the GTEST_HAS_DOWNCAST_ customization point.
      Bump version to v1.14 in preparation for release

Dino Radakovic (16):
      Add IsEmpty overload for C-style strings
      Explicitly instantiate matchee std::string in MatchesRegex
      gtest_unittest: Call FAIL() in lambda, fix incorrect fatality expectation
      Add Windows CI script
      Use git commit hash in CMake quickstart
      Comment that q0_ in primer should remain empty
      Announce that GitHub actions are not GoogleTest's canonical CI
      Update googletest's test docker containers
      Avoid redundant declaration of static constexpr members in c++17
      Fix indentation syntax error in feature request issue template
      Use GTEST_INTERNAL_CPLUSPLUS_LANG instead of __cplusplus
      Explicitly document googletest release tag format
      Fix typo in version number example in README
      Provide example for setting C++ language standard in GoogleTest's Bazel quickstart and readme.
      Copy supported platforms from README onto https://google.github.io/googletest/platforms.html
      Skip entire test suite with `GTEST_SKIP()` in `SetUpTestSuite`

Ferenc Géczi (1):
      Suggests a release with fixed CMakeLists.txt

Gaspard Petit (1):
      Fix for undefined symbol: testing::internal::Random::kMaxRange

Gonzalo Brito Gadeschi (1):
      Fix warnings with nvc++ as the compiler

Hardik Vala (1):
      Add support of 19-member structs to gmock UnpackStructImpl.

Ikko Eltociear Ashimine (1):
      Fix typo in googletest-catch-exceptions-test.py

Jan (1):
      Fix table markup in testing.md

Jeryl Vaz (1):
      Suppress a clang-tidy warning in the MATCHER_P macro

Joakim Plate (1):
      Check for file system for current directory

John Hinnegan (1):
      Update link to Bazel installation guide

Juan Ramos (3):
      cmake: Raise min to 3.6
      cmake: Clean up policy code
      cmake: Remove remaining checks for CMAKE_VERSION

Julian Arkenau (1):
      docs: update googletest README for release 1.12.0

Julien Combattelli (1):
      Use #if and not #ifdef to check filesystem support

Jérôme Travert (2):
      Avoid implicit conversion from int to char
      Avoid implicit conversion from int to char

Kasra Hashemi (1):
      Update README.md

Keith Smiley (1):
      bazel: move -std=c++14 to .bazelrc

Lawrence Wolf-Sonkin (1):
      [gtest] Drop custom-rolled heterogeneous comparator functors in favor of C++ standard ones

Maciej Sroczyński (1):
      Add COMPONENT to install

Marat Dukhan (1):
      Port GoogleTest to QuRT (Hexagon RTOS)

Martijn Vels (1):
      Fix GTEST_HAS_ABSL define check for [-Werror=undef] compilations

Matei Dibu (1):
      gtest-death-test: add 'noreturn'

Mike Kruskal (1):
      Fix C++20 compatibility bug.

Niranjan Nilakantan (2):
      Build googletest with IntelLLVM compilers.
      Ignore the .cache directory create by VSCode.

Patryk Gawroński (1):
      gmock: fix issue #4222

Paul Groke (1):
      work around GCC 6~11 ADL bug

Paul Wankadia (1):
      Update GoogleTest to RE2 release `2023-06-01`.

Phoebe Liang (3):
      Reorder printers list.
      Revise documentation to include AbslStringify
      Make testing::Message support streamed AbslStringify values

Pro3757 (2):
      fix README table
      change table to unordered list

RerEngineer (2):
      fixing gcc.gnu domain redirection
      commit 9c990a7b1e9a1f888aaf16bd38eb52ba16827582

Robert Adam (1):
      Set cmake policy CMP0069

Ryan Schmidt (1):
      Change C++11 requirement to C++14

Sergey (2):
      Fix error in_death_test_child_process: undeclared identifier
      Environment variables are accessible in UWP/WinRT apps

Shlomi Nissan (1):
      Add CXX_STANDARD_REQUIRED to CMake quickstart

Steve Robbins (1):
      Use template type FloatType in the cast.

SunBlack (1):
      Fix typos found by codespell

Tom Hughes (48):
      Fall back to the system clock when building with newlib on a system without a monotonic clock.
      Fix _MSC_VER check
      IWYU: Add missing std includes
      Fix GTEST_OS_ESP8266 check
      Fix -Wshadow warnings
      Fix -Wimplicit-int-float-conversion warning
      Replace deprecated python calls
      Fix formatting of Markdown files
      Fix formatting of C++ files
      Replace numeric lints with their string equivalent
      Fix formatting in subset of Python files
      Remove pylint disable comments that no longer trigger warnings
      Fix pylint warning
      Use more specific assertLess instead of assertTrue
      Fix Python docstrings to match style guide
      Fix formatting in Python files
      Test current behavior of doubles and floats in RecordProperty
      Use explicit short to fix MSVC compiler warning
      Use GTEST_DISABLE_MSC_WARNINGS macros to disable warnings
      Fix sign conversion warning from clang:
      Fix gmock_output_test when using MSVC
      Build gmock Python tests when building with cmake
      Remove GMOCK_RENAME_MAIN
      Fix include order
      Remove unneccessary "#if _MSC_VER"
      Fix -Wsign-conversion warnings
      Fix compiler flags in Linux presubmit
      Remove GTEST_USES_PCRE references
      Fix _MSC_VER check
      Remove int64_t cast in RecordProperty
      Use "#ifdef GTEST_OS_..." instead of "#if GTEST_OS_..."
      Always specify definitions for internal macros
      Only define GTEST_IS_THREADSAFE to 1, not 0
      Use "#ifdef" with public macros
      Replace "#if GTEST_HAS_ABSL" with "#ifdef GTEST_HAS_ABSL"
      Remove GTEST_FOR_GOOGLE_ macro
      Always specify definitions for internal macros
      Fix compilation with -Wundef.
      Fix compilation of googletest-printers-test.cc when using -Wundef
      Add -Wundef to the CI scripts when building with Bazel
      Make parameter names in function declaration match the names in the
      Add missing std includes
      Fix spelling
      Use std::make_unique
      Add missing std includes
      Use the empty method to check for emptiness
      Use '=default' to define trivial constructor/destructors
      Add qualifier to avoid argument dependent lookup

Vertexwahn (2):
      Update rules_python, bazel_skylib and platfroms
      Fix spelling

Vũ Phạm (1):
      Fix typo

Yonggang Luo (2):
      Revert "Fix gmock_output_test when using MSVC"
      Fixes the test gmock_output_test.py with MSVC

Yuriy Chernyshov (1):
      Continuation for #3183

assafpr (14):
      change link from master to main in documentation
      Update gmock_output_test_golden.txt
      documentation, change mater branch to main
      documentation, change mater branch to main
      Update CONTRIBUTING.md
      Update faq.md
      documentation, change mater branch to main
      Update advanced.md
      Update gmock-spec-builders.cc
      Update gtest-death-test.cc
      Update gmock-spec-builders_test.cc
      Update gmock-actions.h
      Update gmock-matchers.h
      Update gtest.cc

gonzalobg (1):
      Add doc comment

kimvaleen (1):
      Fixed variables that could be declared 'const'

niranjan (1):
      Disable some warnings for IntelLLVM on Windows.

pateldeev (1):
      Add missing absl dependency from build.

yagneshprajapati (4):
      Update README.md
      Update README.md
      Update README.md
      Update README.md

yutotnh (3):
      fix: some typos in comment
      fix: typo in test name
      fix: some typos in source